[gspread]
type = "service_account"
project_id = "isentropic-snow-466617-e2"
private_key_id = "265378ba5fb808f8fed528d109ded03e8808588"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCh/2ttwD3Hw+3k
Sp4LILcaoR8tnb4mNEYbJYWQkdKiZPur8TvugyXzadwxPzYRp1xYhIpyb3p8t8HT
Yni5OWSxBviUH0KXpyFce/V/QNaEKCZWtxa9qrAXZlwJSqdN8dcY3mBxktEQB5Jj
2lyfJWh2T0AUgN10slmJ6EXMT1bVl88IatxO+U/8wCrlOI007oYjWRqCs1ukFWg3
iloem6Tc9gn8dpYqFFf/LYg4gk/GR5gZOZF7M4SyHQJKTakGtg+hCPvSQkOgFvqs
nFBii0KqO6pBAPei669UV4Ljz8eDJCGTvnt12mmblFqxH4Oy3miHc4YNZGWxtdSW
vs5ZbQCLAgMBAAECggEAJOPRRvDcIL2RUsdbLhWJHNtMCks9nd2RiWUGAWHzoV91
oDYS+8GJxuB4cA6A9YwzD0U/ccfJENWXodduvl8/esCnorNrqrU4d6MSyKOvNfEe
qeiPmSlhaDK7CrKhXrKP1O3u8G4KhafzwiFbrjIKk8aARSsDQyvKEAmAu4HluEW4
zGizwSuGj+NRZia+ZWDM9gkheqkUMthidrUISSG3HPkLXNrjCkuivAm4uTaNBYJ1
oHo0YaumFkjq+n2phRMLedGhYsKwyB+jZA9rTjSTJQrkZLAHp6G+a+baqGo6rRyF
5N4gigUzv6Ux/bjgZopV+8I/izFTsI/ZLAeQDV4QYQKBgQDXuvlB5TTI8e8xKcYP
P2fePiQ/ppWrrPSk1bHzlsqCfNdUI8HHFHs0qeBWajX8GeXmuCVKX+AUzF78hJbx
0P3nmLjp8JOh6ZwLQ05aNeAls03pv0OhH2rZY+UmYcUZIbnbidXY/hIeTpsup2ZJ
ZeymYCQMfDPxqpK/4d4BWX5XjQKBgQDAPL6nfIMBZEHS8J7x2LjF1MWSIdpT4uBy
+1gb6N8yLeQ+xKHfiBHQHBHC8YJ+a0aJU6I53cdDILL0N5o9lA3qMjeWky+ia1cg
ecrZvYPpRS7GEl8OVlTABeav9JzG0Ytubb4AQtnUPYTXusSU0BaG1blb1Ro9yki4
bCJlCHkGdwKBgQCv/8d4/iD5S4AEEPuX1vfLddEm6KY04C7bB8hdXYkrueQGrgFa
hJgbl/gBKDeQzCQm/dbWfa+X6EAaLaXj9MggmRVLLk2Ti74V5jxXFpsextDqwXLQ
UYxffMMndB5T6ZLyy9neZTGs7h5mioXFndTay5a9ZNsP70Q4LXJskXGkxQKBgGHD
Qq5ImxMtGnCdICgcMDOjtmpPvwmkOsMe4bsn3cJWJlppg2z7dRuh+sJqMhP6mF+k
Yb8N85VG3ttmH5GrZrwwl6aC6dmuvxtr9OZxA9Gw9k2S8DaJXwZcuenH+6b8z+zz
8ImPddoDAzj26ZxIivw9WsvB/1tnMT5g98jr2yiXAoGBAMnlfEtSU7RavRot8+dY
RY/IDCJf75GsYWZD0bQul+O164tS5LI7Yw/NWPnAF3h8V2lS6cDPlyC1HYpG2j82
jjjN0kB19M5+mYL8/7pbjJWV7xmRcwnB1xA9c05/r6v9vHccBNrxeyV2Uyqm9LAa
jtQEe8NfSsFSQZfeejxcAhft
-----END PRIVATE KEY-----
"""
client_email = "streamlitsheetsaccess@isentropic-snow-466617-e2.iam.gserviceaccount.com"
client_id = "100133783425077047371"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlitsheetsaccess%40isentropic-snow-466617-e2.iam.gserviceaccount.com"

sheet_url = "https://docs.google.com/spreadsheets/d/1-IJvUsk09SoK9pO037Ao_fVo9342Z-bOlF1OPA-t56g"
